# Generated by Django 5.0.11 on 2026-02-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgogramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('interpretation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('character_image_url', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('tendency_personality', models.TextField(blank=True)),
                ('tendency_behavior_pattern', models.TextField(blank=True)),
                ('preference_likes', models.TextField(blank=True)),
                ('preference_dislikes', models.TextField(blank=True)),
                ('coaching_tips', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='accounts.user')),
            ],
        ),
    ]
