# Generated by Django 5.0.11 on 2026-02-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCheckEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.TextField(blank=True)),
                ('sleep_pattern', models.CharField(blank=True, max_length=50)),
                ('exercise_flag', models.BooleanField(default=False)),
                ('exercise_per_week', models.IntegerField(blank=True, null=True)),
                ('exercise_type', models.CharField(blank=True, max_length=20)),
                ('pet_type', models.CharField(blank=True, max_length=100)),
                ('mbti', models.CharField(blank=True, max_length=4)),
                ('outing_per_week', models.IntegerField(blank=True, null=True)),
                ('speech_audio_path', models.CharField(blank=True, max_length=255, null=True)),
                ('self_intro_doc_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_check_entries', to='accounts.user')),
            ],
        ),
    ]
